"""empty message

Revision ID: 7a3a8f19c84a
Revises: cd17e11e4516
Create Date: 2023-06-13 18:27:39.256523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3a8f19c84a'
down_revision = 'cd17e11e4516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
